"""update user model fields

Revision ID: 37964ca5df08
Revises: 51b9a5ad36bd
Create Date: 2026-04-09 17:54:44.918944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '37964ca5df08'
down_revision: Union[str, Sequence[str], None] = '51b9a5ad36bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Création explicite du type ENUM pour PostgreSQL
    fieldstatus_enum = postgresql.ENUM('pending', 'approved', 'rejected', name='fieldstatus')
    fieldstatus_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fieldofstudy', sa.Column('status', fieldstatus_enum, nullable=True))
    op.add_column('fieldofstudy', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fieldofstudy', 'user', ['submitted_by'], ['id'])
    op.add_column('memoir', sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('memoir', 'is_premium')
    op.add_column('university', sa.Column('acronym', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('university_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'university', ['university_id'], ['id'])
    op.create_foreign_key(None, 'user', 'country', ['country_id'], ['id'])
    op.drop_column('user', 'is_premium')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'country_id')
    op.drop_column('user', 'university_id')
    op.drop_column('university', 'acronym')
    op.add_column('memoir', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('memoir', 'rejection_reason')
    op.drop_constraint(None, 'fieldofstudy', type_='foreignkey')
    op.drop_column('fieldofstudy', 'submitted_by')
    op.drop_column('fieldofstudy', 'status')
    # ### end Alembic commands ###
