"""add public_id to memoir

Revision ID: 42c23ef16255
Revises: 37964ca5df08
Create Date: 2026-04-10 15:06:48.173572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c23ef16255'
down_revision: Union[str, Sequence[str], None] = '37964ca5df08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memoir', sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_memoir_public_id'), 'memoir', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memoir_public_id'), table_name='memoir')
    op.drop_column('memoir', 'public_id')
    # ### end Alembic commands ###
