"""Add author contact checks

Revision ID: 51b9a5ad36bd
Revises: b5bd0f557029
Create Date: 2026-04-05 15:25:16.327280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51b9a5ad36bd'
down_revision: Union[str, Sequence[str], None] = 'b5bd0f557029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # La ligne altérant fieldstatus a été retirée car c'était un faux positif d'Alembic
    op.add_column('memoir', sa.Column('author_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('memoir', sa.Column('author_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memoir', 'author_phone')
    op.drop_column('memoir', 'author_email')
    # ### end Alembic commands ###
