"""add public_id to user and university

Revision ID: ddd7f0103644
Revises: 42c23ef16255
Create Date: 2026-04-10 15:40:03.604495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd7f0103644'
down_revision: Union[str, Sequence[str], None] = '42c23ef16255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_university_public_id'), 'university', ['public_id'], unique=True)
    op.add_column('user', sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_user_public_id'), 'user', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_public_id'), table_name='user')
    op.drop_column('user', 'public_id')
    op.drop_index(op.f('ix_university_public_id'), table_name='university')
    op.drop_column('university', 'public_id')
    # ### end Alembic commands ###
