"""add public_id to field and application

Revision ID: ef8d3d250843
Revises: ddd7f0103644
Create Date: 2026-04-10 15:57:57.299597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8d3d250843'
down_revision: Union[str, Sequence[str], None] = 'ddd7f0103644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fieldofstudy', sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_fieldofstudy_public_id'), 'fieldofstudy', ['public_id'], unique=True)
    op.add_column('team_applications', sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_team_applications_public_id'), 'team_applications', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_applications_public_id'), table_name='team_applications')
    op.drop_column('team_applications', 'public_id')
    op.drop_index(op.f('ix_fieldofstudy_public_id'), table_name='fieldofstudy')
    op.drop_column('fieldofstudy', 'public_id')
    # ### end Alembic commands ###
